### ISSUE TITLE
Function sigma does not belong to geometry

### ISSUE THREAD

**Issue by bitobs** [davidomarf/viare#38]
## Current State
Function `sigma` is inside `geometry.d` but does not belong there.

## Solution
There are two possibilities:
- We remove sigma function as is not used anywhere.
- We create a math.d module and place `sigma` there.

**Comment by davidomarf** [comment]
I'd suggest creating module math. 

Could it be convenient to make geometry a submodule of math?

**Comment by bitobs** [comment]
I think it would be.

**Comment by bitobs** [comment]
Solved by https://github.com/davidomarf/viare/pull/39
